// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbEPO9sdFDeWIa9FLGJkF2sDHGe08XH0',
    appId: '1:496969072737:web:fd5eed473aec9ceef36a20',
    messagingSenderId: '496969072737',
    projectId: 'dailybachat',
    authDomain: 'dailybachat.firebaseapp.com',
    storageBucket: 'dailybachat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2vZ3uzPiy4j3sAiKH9QFL2zbPcYrNno',
    appId: '1:496969072737:android:4664c238751a708cf36a20',
    messagingSenderId: '496969072737',
    projectId: 'dailybachat',
    storageBucket: 'dailybachat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOirYSFD8qeWgONtUs8ML35y-ZlHdvBU',
    appId: '1:496969072737:ios:5739cb4b09300d73f36a20',
    messagingSenderId: '496969072737',
    projectId: 'dailybachat',
    storageBucket: 'dailybachat.firebasestorage.app',
    iosBundleId: 'com.technosolz.dailybachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATOirYSFD8qeWgONtUs8ML35y-ZlHdvBU',
    appId: '1:496969072737:ios:5739cb4b09300d73f36a20',
    messagingSenderId: '496969072737',
    projectId: 'dailybachat',
    storageBucket: 'dailybachat.firebasestorage.app',
    iosBundleId: 'com.technosolz.dailybachat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbEPO9sdFDeWIa9FLGJkF2sDHGe08XH0',
    appId: '1:496969072737:web:9b21daf161d6487bf36a20',
    messagingSenderId: '496969072737',
    projectId: 'dailybachat',
    authDomain: 'dailybachat.firebaseapp.com',
    storageBucket: 'dailybachat.firebasestorage.app',
  );

}