on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (required for Android builds)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          cache: true

      # Step 4: Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Run tests (optional, if you have tests)
      - name: Run Flutter tests
        run: flutter test
        continue-on-error: true

      # Step 6: Force correct Java home for Gradle
      - name: Set Gradle Java Home
        run: echo "org.gradle.java.home=${JAVA_HOME}" >> android/gradle.properties
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      # Step 7: Build the APK (for Android)
      - name: Build APK
        run: flutter build apk --release
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      # Step 8: Debug APK existence
      - name: Debug APK
        run: ls -la build/app/outputs/flutter-apk/

      # Step 9: Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
